## Python basics

In [2]:
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [5]:
a+2

TypeError: can only concatenate list (not "int") to list

In [4]:
import numpy as np

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = a1 + a2
print(a3)

[5 7 9]


In [6]:
a1+2

array([3, 4, 5])

In [7]:
a1.ndim

1

In [8]:
a1.shape

(3,)

In [11]:
a1=a1.reshape(-1,1)

In [12]:
a1.ndim

2

In [13]:
print(a1)

[[1]
 [2]
 [3]]


In [19]:
import array
aa =array.array('i',[1,2,3])
aa

array('i', [1, 2, 3])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [26]:
import random

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

NPS : Net promoter score

* 1-6 : Negative feeling about the service -->Detractors/Demoters
* 7-8 : Neutral -->Promoters
* 9-10 : Positive feeling about the service --->Promoters

NPS = Promoters-Detractors/(Tot No of people) * 100

In [29]:
scores = np.loadtxt('/content/survey.txt')
type(scores[0])

numpy.float64

## Default the this creates an array , takes the values as float, in order to convert into u can do the below

In [30]:
scores = np.loadtxt('/content/survey.txt',dtype='int')
type(scores[0])

numpy.int64

In [31]:
len(scores)

1167

## Totally we have 1167 reviews   

In [42]:
## Promoters

promoters = scores[scores >= 7]
no_of_prom = len(promoters)
no_of_prom

835

In [37]:
demoters = scores[scores < 7]
no_of_dem=len(demoters)

In [39]:
tot_reviews = len(scores)

In [41]:
NPS = ((no_of_prom - no_of_dem)/tot_reviews) * 100
NPS

43.10197086546701

In [44]:
ary = np.arange(1,10)
ary

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
ary.ndim

1

In [54]:
tdArry = ary.reshape(1,-1)
tdArry

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
ary.reshape(-1,1).ndim

2

In [55]:
import pandas as pd
df = pd.read_csv('/content/mckinsey.csv')
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [56]:
df.shape

(1704, 6)

In [57]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Leba

In [58]:
df['country'].value_counts()

country
Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Name: count, Length: 142, dtype: int64

In [59]:
df['country'].shape

(1704,)

In [61]:
type(df['country'])

pandas.core.series.Series

In [63]:
df['country'].values

array(['Afghanistan', 'Afghanistan', 'Afghanistan', ..., 'Zimbabwe',
       'Zimbabwe', 'Zimbabwe'], dtype=object)

*** Always the columns in the dataframe will be as series , where the series can be accessed with the labels

* accessing the column with "values" gives us the type as array



In [64]:
df['life_exp'].max(),df['life_exp'].min()

(82.603, 23.599)

In [65]:
df['country']=='India'

0       False
1       False
2       False
3       False
4       False
        ...  
1699    False
1700    False
1701    False
1702    False
1703    False
Name: country, Length: 1704, dtype: bool

In [67]:
df[df['country']=='India']

country  year  population continent  life_exp      gdp_cap
696   India  1952   372000000      Asia    37.373   546.565749
697   India  1957   409000000      Asia    40.249   590.061996
698   India  1962   454000000      Asia    43.605   658.347151
699   India  1967   506000000      Asia    47.193   700.770611
700   India  1972   567000000      Asia    50.651   724.032527
701   India  1977   634000000      Asia    54.208   813.337323
702   India  1982   708000000      Asia    56.596   855.723538
703   India  1987   788000000      Asia    58.553   976.512676
704   India  1992   872000000      Asia    60.223  1164.406809
705   India  1997   959000000      Asia    61.765  1458.817442
706   India  2002  1034172547      Asia    62.879  1746.769454
707   India  2007  1110396331      Asia    64.698  2452.210407

In [68]:
def check(ls):
  ls[0]=100

list1 = [1,2,4]
check(list1)
list1

[100, 2, 4]

## So list is pass by reference , what ever the changes that u r making in the function is reflected in the original list as well

*Pass by reference is for mutable objects like list and dictionary

* Immutable Objects: When passing immutable objects (such as integers, floats, strings, and tuples) to a
function, any modifications to the parameter within the function do not affect the original argument. This
behavior is akin to "pass by value".
* Mutable Objects: When passing mutable objects (such as lists, dictionaries, and sets) to a function,
modifications to the parameter within the function do affect the original argument. This behavior is more
like "pass by reference".